# -*- coding: utf-8 -*-
"""Data Science Tasks 2(GRIP).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E6zUAEJNEAhpriBOU2Nuk8aJiGLHvwaw?usp=sharing

#GRIP @ THE SPARKS FOUNDATION

---



##INTERNSHIP TASK-2

# Exploratory Data Analysis - Retail

##By Samarth Agarwal
"""

!pip install dataprep  
!pip install pandas-profiling==2.7.1
#would require to restart runtime

# Dataset: https://bit.ly/3i4rbWl

"""LOAD LIBRARIES"""

from dataprep.eda import plot,plot_correlation

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

df=pd.read_excel('/content/SampleSuperstore.xlsx')

df.info()

df.head()

df.describe().T

"""##**DESCRIPTIVE STATISTICS & MISSING VALUES**


---





"""

import pandas_profiling as pp
pp.ProfileReport(df)

"""##Removing constant columns & duplicate rows 

---



---


"""

df=df.drop('Country',axis=1)

df.drop_duplicates(inplace=True)

plot(df,'Profit')

"""##Analysing profit by sales,quantity& category"""

plot(df,'Sales','Profit')

plot(df,'Quantity','Profit')

plot(df,'Discount','Profit')



"""##Conclusions
-Prominent outliers in sales,discount.  
-With increase in discount the profit decreases.

"""

print(df['Discount'].quantile(0.10),df['Discount'].quantile(0.90))
print(df['Sales'].quantile(0.10),df['Sales'].quantile(0.90))

df2=df.copy()
df2["Sales"] = np.where(df["Sales"] <7.8936,7.8936,df['Sales'])
df2["Sales"] = np.where(df["Sales"] >572.949,572.949,df['Sales'])
df2["Discount"] = np.where(df["Discount"] <0.0, 0.0,df['Discount'])
df2["Discount"] = np.where(df["Discount"] >0.4, 0.4,df['Discount'])

plot(df2,'Discount','Profit')

plot(df2,'Sales','Profit')



"""##Quantity and sales have high correlation with profit

---



---


"""

plot_correlation(df2)

plot_correlation(df2,'Profit')



